language: generic 

sudo: required
services:
    - docker

before_install:
    - docker build -t josefernandesfeedzai/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true josefernandesfeedzai/docker-react npm run test -- --coverage
    